version: '3.8'

services:
  nginx:
    build:
      context: ./services/nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
    restart: always

  stocks1-a:
    build:
      context: ./services/stocks-service
    ports:
      - "${STOCKS1_PORT}:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=${MONGODB_URI}
      - STOCKS1_COLLECTION=${STOCKS1_COLLECTION}
      - NINJA_API_KEY=${NINJA_API_KEY}
      - NINJA_API_URL=${NINJA_API_URL}
    depends_on:
      - mongodb
    restart: always

  stocks1-b:
    build:
      context: ./services/stocks-service
    environment:
      - PORT=5001
      - MONGODB_URI=${MONGODB_URI}
      - STOCKS1_COLLECTION=${STOCKS1_COLLECTION}
      - NINJA_API_KEY=${NINJA_API_KEY}
      - NINJA_API_URL=${NINJA_API_URL}
    depends_on:
      - mongodb
    restart: always

  stocks2:
    build:
      context: ./services/stocks-service
    ports:
      - "${STOCKS2_PORT}:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=${MONGODB_URI}
      - STOCKS2_COLLECTION=${STOCKS2_COLLECTION}
      - NINJA_API_KEY=${NINJA_API_KEY}
      - NINJA_API_URL=${NINJA_API_URL}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./logs/mongodb:/logs/mongodb
    command: mongod --logpath /logs/mongodb/mongod.log
    restart: always

volumes:
  mongodb_data:
